[Team5 Pair1] Step2 코드리뷰 요청드립니다~
wwh-techcamp-2018/java-qna-atdd pull request #14
Opened 2018-07-17 05:39 UTC by Lahavas

2018-07-17 05:43 UTC, javajigi requested changes
구현 잘 했네요. Exception  처리에 대한 피드백 남겨요.

2018-07-17 05:43 UTC, javajigi commented on src/main/java/codesquad/web/QnaController.java
> +    public String showCreateForm(@LoginUser(required = false) User user) {
굳이 exception을 throw하는 (required = false) 설정해야 되나요?

2018-07-17 05:43 UTC, javajigi commented on src/main/java/codesquad/service/QnaService.java
> +        return questionRepository.findByIdAndWriter(id, user);
여기서 Optional로 반환하지 말고 orElseThrow 처리하면 어떨까요?

2018-07-17 05:43 UTC, javajigi commented on src/test/java/codesquad/domain/QuestionTest.java
> +    }
테스트 코드 👍

2018-07-17 08:31 UTC, merged

2018-07-22 11:55 UTC, minsungryu commented on src/main/java/codesquad/service/QnaService.java
> +        return questionRepository.findByIdAndWriter(id, user).orElse(null);
`Optional`을 통해 값을 받은 뒤 굳이 `null`을 반환하시는 이유가 있나요?
`Optional<Question>`을 반환하는 편이 코드의 일관성이나 예외처리 면에서 더 좋을 것 같습니다.

2018-07-22 12:05 UTC, minsungryu commented on src/main/java/codesquad/web/QnaController.java
> +        } catch (UnAuthorizedException ex) {
중복되는 `UnAuthorizedException`에 대해 컨트롤러 내에 `@ExceptionHandler`를 통해 처리하면 좋을 것 같습니다.